### PR TITLE
Responsive footer with stick at end of screen

### LINKED ISSUE #35: Irresponsive footer on expense and To-do Page
**Describe the bug**
I have found that the footer on expense and to-do page are irresponsive . The idea I would like to implement is fix it to the bottom .

**To Reproduce**
1. Go to Home Page
2. Click on Expense/Todo to move to the respective route page
3. You will find the problem 

**Expected behavior**
To Fix the footer at the bottom .

**check list**
- [ ] I am contributing under GSSoC-ext
- [ ] I am contributing under hacktoberfest
- [ ] I follow contribution guidlines

**Additional context**
This will help in better UI/UX

### PR DESCRIPTION
**Pull request by prathamesh-pichkate**
### 🛠️ Fixes Issue
Closes #35

### 👨‍💻 Description
-Made the footer responsive and stick at end when user see at laptop view.

### 📄 Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
image
image

### ✅ Checklist
- [X] I am a participant of GSSoC-ext.
- [X] I have followed the contribution guidelines of this project.
- [X] I have viewed deployment of my code.
- [X] My changes generate no new warnings.
- [X] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [X] This PR is submitted under the GSSoC program.
- [X] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by prathamesh-pichkate** [comment]
@divyansh-2005 Hey add the hacktoberfest and gssoc tag

**Review by divyansh-2005 — COMMENTED** [review]
footer is already responsive.

**Comment by prathamesh-pichkate** [comment]
But when it is viewed at the mobile view there is margin which was fixed and was asked to stick at bottom .

**Comment by kottarivaibhav** [comment]
Yup this is the change what I meant , its done mostly now by @prathamesh-pichkate

**Comment by divyansh-2005** [comment]
But do not see any change in behavior of footer

**Pull request closed without merging**
