### PR TITLE
Sucessfully added and linked AboutUs and ContactUs Pages #55

### LINKED ISSUE #55: [FEATURE] Add About us and Contact us pages and also link it with the home page
### Feature Request

**Is your feature request related to a problem? Please describe.**
I'm frustrated that there is no "About Us" and "Contact Us" page on the site, which makes it difficult for users to learn more about the organization and how to get in touch.

**Describe the solution you'd like**
I would like to create an "About Us" page and a "Contact Us" page. These pages will include relevant information about the organization, team, mission, and ways to get in touch. I will link these pages to the homepage for easy navigation.

**Screenshots**
Screenshot 2024-10-05 121129

**Screenshots/Video of Feature**
(Optional: I can create a video or screenshots explaining the feature during the development process.)

### Checklist
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under Hacktoberfest
- [x] I follow contribution guidelines

I will design the "About Us" and "Contact Us" pages, link them to the homepage, and ensure they are populated with appropriate information about the organization.

Please provide me with the necessary codebase access or guidelines to proceed with the development.

### PR DESCRIPTION
**Pull request by yeshwanth-ds**
### 🛠️ Fixes Issue  
Closes #55 

### 👨‍💻 Description  
- Implemented enhancements to the **About Us** and **Contact Us** pages to improve user experience and accessibility.
- Major changes include:
  - Streamlined design for both pages to align with the overall theme of the application.
  - Updated styles to enhance visual appeal, including responsive design adjustments.
  - Added improved form validation for the Contact Us page to ensure user inputs are correctly captured.
- These enhancements provide a more cohesive look and feel, making it easier for users to navigate and engage with the content.

### 📄 Type of Change  
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)  

https://github.com/user-attachments/assets/7fbc27fe-4d06-4a48-b654-a53dcce641a0

Screenshot 2024-10-06 145302

Screenshot 2024-10-06 145310

### ✅ Checklist  
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed the deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation  
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### 🎟️ Labels
- GSSoC-ext
- Hacktoberfest
- Level 3 
As mentioned earlier when the request was raised.

### CODE REVIEW

**Comment by akashkumar241203** [comment]
needs to improve the styling can you work on it?

**Comment by yeshwanth-ds** [comment]
@akashkumar241203 Sure!! 

If u hav any recommendations or leads let on this task tell me i make chnages accordingly

**Comment by akashkumar241203** [comment]
Like the input field need to look good as they are not managed properly

**Comment by yeshwanth-ds** [comment]
@akashkumar241203 I will work on that and let me know uf there is anything more

**Comment by yeshwanth-ds** [comment]
@akashkumar241203 

**I made few chaneges for the contactus page** 

**Before**

Screenshot 2024-10-06 145310


**After**

Screenshot 2024-10-06 233811

Screenshot 2024-10-06 233818

Added Sufficient spacing in the form tag and made a hover design change for the "submit message" button to same as the "Add Expense" button form the expense page.

Lets me kown for any other chnges

**Comment by yeshwanth-ds** [comment]
@akashkumar241203 Could you review this PR s and assign me the tags.

**Comment by divyansh-2005** [comment]
@akashkumar241203 make a issue and raise pr for styling change

**Pull request merged**
